name: Repology metadata

on:
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}
    - name: Clone Termux package repositories
      run: |
        mkdir -p /tmp/repos
        git clone --depth=1 https://github.com/termux/termux-packages /tmp/repos/main
        git clone --depth=1 https://github.com/termux/game-packages /tmp/repos/games
        git clone --depth=1 https://github.com/termux/science-packages /tmp/repos/science
        git clone --depth=1 https://github.com/termux/termux-root-packages /tmp/repos/root
        git clone --depth=1 https://github.com/termux/unstable-packages /tmp/repos/unstable
        git clone --depth=1 https://github.com/termux/x11-packages /tmp/repos/x11
    - name: Generate packages.json
      run: |
        bash ./generate-repology-metadata.sh /tmp/repos/*/packages/* > ./packages.json
        if [ $(git diff ./packages.json | wc -l) -gt 0 ]; then
          git config --global user.name "Termux Github Actions"
          git config --global user.email "contact@termux.com"
          git add ./packages.json
          git commit -m "Generate new metadata for Repology"
          git push
        fi
